GET http://localhost:3001/api/contactforms

###

POST http://localhost:3001/api/contactforms
Content-Type: application/json

{
    "email": "test@message.com",
    "message": "message"
}

###

GET http://localhost:3001/api/consultations