GET http://localhost:3001/api/contactforms

###

POST http://localhost:3001/api/contactforms
Content-Type: application/json

{
    "email": "test@message.com",
    "message": "message"
}

###

GET http://localhost:3001/api/consultations

###

POST http://localhost:3001/api/consultations
Content-Type: application/json

{
  "summary": "New Event",
  "location": "Some Place",
  "description": "Event Description",
  "start": {
    "dateTime": "2023-08-12T09:00:00+01:00",
    "timeZone": "Europe/Madrid"
  },
  "end": {
    "dateTime": "2023-08-12T17:00:00+01:00",
    "timeZone": "Europe/Madrid"
  }
}






