GET http://localhost:3001/api/contactforms

###

POST http://localhost:3001/api/contactforms
Content-Type: application/json

{
    "email": "test@message.com",
    "message": "message"
}

###

GET http://localhost:3001/api/consultations

###

POST http://localhost:3001/api/consultations
Content-Type: application/json

{
  "summary": "New Event",
  "location": "Some Place",
  "description": "Event Description",
  "start": {
    "dateTime": "2023-08-19T09:00:00+01:00",
    "timeZone": "Europe/Madrid"
  },
  "end": {
    "dateTime": "2023-08-19T10:00:00+01:00",
    "timeZone": "Europe/Madrid"
  }
}

###

GET http://localhost:3001/api/trainingvideos


###

POST http://localhost:3001/api/trainingvideos
Content-Type: application/json


{
    "embedUrl":"https://youtube.com/embed/NsPJJplFNN4",
    "title":"Muscle Building vs Fat Loss: Insight from Bullet Point Fitness",
    "dateAdded":"2023-10-16",
    "description": "Which is harder—building muscle or losing body fat? Explore the challenges and intricacies of each process, from the physiological demands to the dietary and training strategies involved. Understand the factors that can influence one's ability to gain muscle mass versus shedding unwanted pounds, and determine which journey might be more challenging for you.",
    "duration": "1 min and 41 seconds"
}

###

GET http://localhost:3001/api/nutritionvideos


###

POST http://localhost:3001/api/nutritionvideos
Content-Type: application/json


{
    "embedUrl":"https://www.youtube.com/embed/5gEZeCL9qZo?si=WBwMgqLQgdaRoIm6",
    "title":"Cs50P Final Project",
    "dateAdded":"2022-10-07"
}

###

GET http://localhost:3001/api/musclefunctionvideos


###

POST http://localhost:3001/api/musclefunctionvideos
Content-Type: application/json


{
    "embedUrl":"https://youtube.com/embed/f4TO3Tbkw4k",
    "title":"Neck Function",
    "dateAdded":"2023-11-02",
    "description": "Explore the function of the Neck with Bullet Point Fitness. Discover the integral role this muscle plays in your movement and overall body mechanics.",
    "duration": "53 seconds",
    "muscleName": "Neck"
}

###

GET http://localhost:3001/api/exercisevideos


###

POST http://localhost:3001/api/exercisevideos
Content-Type: application/json


{
    "embedUrl":"https://youtube.com/embed/J7e_zP9gvOs",
    "title":"Triceps Extension with Bullet Point Fitness",
    "dateAdded":"2023-11-03",
    "description": "Explore the mechanics of the Triceps Extension with Bullet Point Fitness. Learn how it targets your triceps, to ensure you train effectively and understand the science behind every rep.",
    "duration": "47 seconds",
    "muscleName": "Triceps"
}

###

GET http://localhost:3001/api/aboutvideos


###

POST http://localhost:3001/api/aboutvideos
Content-Type: application/json


{
    "embedUrl":"https://youtube.com/embed/VUIpLitgB84",
    "title":"Welcome Video",
    "dateAdded":"2023-09-27",
    "description": "Watch to find out about Bullet Point Fitness.",
    "duration": "1 min and 20 seconds"
}

###

GET http://localhost:3001/api/organs


###

POST http://localhost:3001/api/organs
Content-Type: application/json


{
    "name": "Heart",
    "function": "The heart is the muscle at the center of your circulatory system, responsible for pumping blood throughout your body with each heartbeat. This process delivers essential oxygen and nutrients to all parts of your body while also carrying away unwanted carbon dioxide and waste products.",
    "nutrients": [
        "Folate (Vitamin B9): Lowers homocysteine levels, reducing the risk of heart disease.",
        "Omega-3 Fatty Acids (ALA): Reduces inflammation and supports overall heart health.",
        "Vitamin C: Aids in the repair of tissues and the enzymatic production of neurotransmitters.",
        "Potassium: Essential for maintaining proper heart function and regulating blood pressure.",
        "Magnesium: Involved in heart rhythm, muscle function, and blood pressure control."
    ],
    "foods": [
        "Folate: Spinach, whole eggs, broccoli, kale.",
        "Omega-3 Fatty Acids (ALA): Walnuts, olive oil, flaxseeds.",
        "Vitamin C: Bell peppers, kale, strawberries, kiwi, bell peppers, oranges.",
        "Potassium: Beans(all kinds), chickpeas, nuts, spinach.",
        "Magnesium: Pumpkin seeds, almonds, flaxseeds, Brazil nuts, cashews."
    ]
}